### ISSUE TITLE
ModuleNotFoundError: No module named 'classaccuracy-master/ClassAccuracyMain'

### ISSUE THREAD

**Issue by nicolasyounes** [remotesensinginfo/classaccuracy#3]
Hi Pete,
I've use the plugin before and found it very useful. 
I got a 'new' computer from my work and when i tried to install the plugin from the zip file, i ran into this error:

```
Couldn't load plugin 'classaccuracy-master/ClassAccuracyMain' 

ModuleNotFoundError: No module named 'classaccuracy-master/ClassAccuracyMain' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'classaccuracy-master/ClassAccuracyMain'
```
is there perhaps something i'm missing? the installation process seems quite straightforward

I have the following set up:
QGIS version | 3.16.7-Hannover
OS Version | Windows 10 (10.0) Enterprise

**Comment by sebastian-ch** [comment]
Having the same issue - QGIS version 3.16.15

**Comment by petebunting** [comment]
Have you downloaded and installed [ClassAccuracy_v1.0.0.zip](https://github.com/remotesensinginfo/classaccuracy/releases/download/qgis3_v1.0.0/ClassAccuracy_v1.0.0.zip) if you install from the 'source code' download or by clone the git repo then you will not have things in the right paths or the build icon etc.
